update 'done()'.
I faced below test failed.
Therefore I updated 'done()' calling.

>  1) ssr
>       spread-element:
>     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/svelte/svelte/test/test.ts)